### ISSUE TITLE
Create User Class

### ISSUE THREAD

**Issue by DinneK** [DinneK/GitFit#4]
### Create a mock user data set for testing suite

- [x] 'copy' 3-5 users from `users.js` file, create a whole new JS file titled `mockUsersData.js` and 'paste' the users.
- [x] import these files into our testing files.

### Create a User
`const user1 = new User(userData);`

- [x] Create the `user.js` class file
- [x] create the constructor 
- [x] export the class - `module.exports = User;`

### properties:

- [x] this.userId
- [x] this.name
- [x] this.address
- [x] this.email
- [x] this.strideLength
- [x] this.dailyStepGoal
- [x] this.friends

### Possible Methods:
- [x] returnFirstName()

## To Think About:
~~- [ ] How to filter the steps goals of an average user compared to an individual user~~
~~- [ ] How to filter a date range~~
~~- [ ] Pull in the month and year~~
~~- [ ] Filter a date range Class~~

**Comment by BertoCruz** [comment]
### Things to Think About:

- when we create a single instance of userClass we will pass in its user info as an object and then we will push this user into the users array in UserRepository.
