### ISSUE TITLE
Dashboard needs

### ISSUE THREAD

**Issue by MattWalterTX** [DinneK/GitFit#6]
#Things the dashboard will include

- [x] Create an info card with all of the user's info on the page
- [x] Display a prominent welcome message with users first name
- [x] for the specific user, display their step goal compared to all users
- [x] Will need a method to pull a random user

##Hydration

- [x] A display to show how much water they have consumed today (these displays are often called “widgets” in the FE tech world)
- [x] A display to show much water they have consumed each day over the course of the latest week

##Sleep

- [x] For a user, their sleep data for the latest day (hours slept and quality of sleep)
- [x] For a user, their sleep data over the course of the latest week (hours slept and quality of sleep)
- [x] For a user, their all-time average sleep quality and all-time average number of hours slept

**Comment by DinneK** [comment]
- [x] Display user's friends
