### ISSUE TITLE
Create Hydration Class

### ISSUE THREAD

**Issue by DinneK** [DinneK/GitFit#9]
### Before we start, consider:

- [x] We will need to create a `mockHydrationData.js` file where we will 'copy' and 'paste' at least 7 'days' of hydration data for each user.
- [x] We will probably only need to test off of 2 users, though. 
- [x] It will be 2 users with 7 days of hydration data.

### Create Hydration Class
`const hydrationData = new Hydration(user1, data)`
`const user1 = new User(data)`

const user1Hydration = hydration.getUserOunces();

- [x] create constructor  
- [x] export module 

### Properties
- [x] `this.hydrationData = data;`
- [ ] `this.userId = data[i][userID];`
- [ ] `this.date = data[i][date]`
- [ ] `this.numOunces = data[i][numOunces]`

### Methods 
- [x] `compareUserIdToHydrationId();`
- [x] `getUserOunces();`
- [x] `getHydrationsDates(timeframe)`
- [x] `getWeeklyHydrationData(user,)`
- [x] `getDates()`
- [x] `getFluidOunces()` ?

### Possible Properties and Methods
- [ ] 

### Notes
- Dani: I think we need to pass in a `User` object as a parameter for every `Hydration` class method, so that we can check the user.id to the hydration.id and pull up their hydration info.
EX:
```
hydrationData.getOunces(user1);
///expect an array of user1's hydration ounces.
```

Create classes and methods that can calculate:

For a user (identified by their userID - this is the same for all methods requiring a specific user’s data), the average fluid ounces consumed per day for all time
For a user, how many fluid ounces they consumed for a specific day (identified by a date)
For a user, how many fluid ounces of water consumed each day over the course of a week (7 days) - return the amount for each day
You have to decide which classes should contain each method. Think about whose responsibility it is to own the method.

**Comment by BertoCruz** [comment]
FUTURE FEATURES
- be able to look into a user's week 'so far', not necessarily a week from the date we give it.
